# Generated by Django 6.0.7 on 2026-08-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Sigla (Opicional)')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_anvisa', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao_detalhada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização Detalhada')),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vida_util_anos', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('funcionamento', 'Em funcionamento'), ('manutencao', 'Em manutenção'), ('interditado', 'Interditado'), ('nao_localizado', 'Não localizado')], default='funcionamento', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamentos/fotos/')),
                ('manual_tecnico', models.FileField(blank=True, null=True, upload_to='equipamentos/manuais/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='equipamentos/qr_codes/')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('data_execucao', models.DateField()),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('defeito_informado', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('solucao_aplicada', models.TextField(blank=True, null=True)),
                ('pecas_utilizadas', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('proxima_preventiva', models.DateField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='OficinaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('data_envio', models.DateField()),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('ordem_servico', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_oficina', to='core.equipamento')),
            ],
        ),
    ]
