# Generated by Django 6.0.7 on 2026-08-07 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='tecnico_responsavel',
            new_name='tecnico',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 7, 15, 31, 27, 500275, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='descricao',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(default='Concluída', max_length=50),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tipo_manutencao',
            field=models.CharField(default=datetime.datetime(2026, 8, 7, 15, 32, 1, 711185, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
