# Generated by Django 6.0.7 on 2026-08-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tecnico_responsavel_manutencao_tecnico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaAcessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acessorio', models.CharField(max_length=100)),
                ('data_troca', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('tecnico', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
    ]
