# Generated by Django 6.0.7 on 2026-08-31 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(blank=True, help_text='Ex: GMBP-01-2026', max_length=50, null=True)),
                ('orgao_cedente', models.CharField(default='SECRETARIA ESTADUAL DE SAUDE DO TOCANTINS', max_length=255)),
                ('unidade_cedente', models.CharField(default='GERENCIA DE ENGENHARIA CLINICA - SES', max_length=255)),
                ('municipio_cedente', models.CharField(default='Palmas', max_length=100)),
                ('orgao_receptor', models.CharField(default='SECRETARIA ESTADUAL DE SAUDE DO TOCANTINS', max_length=255)),
                ('unidade_receptor', models.CharField(help_text='Ex: ENGENHARIA CLINICA - HGP', max_length=255)),
                ('municipio_receptor', models.CharField(default='Palmas', max_length=100)),
                ('tipo_movimentacao', models.CharField(choices=[('TRANSFERENCIA_INTERNA', 'Transferência Interna'), ('TRANSFERENCIA_EXTERNA', 'Transferência Externa'), ('EMPRESTIMO_INTERNO', 'Empréstimo Interno'), ('EMPRESTIMO_EXTERNO', 'Empréstimo Externo'), ('DEVOLUCAO', 'Devolução')], max_length=50)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_conservacao', models.CharField(choices=[('RUIM', 'Ruim'), ('INTERMEDIARIO', 'Intermediário'), ('PERFEITO', 'Perfeito')], default='PERFEITO', max_length=20)),
                ('quantidade', models.IntegerField(default=1)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao_editada', models.TextField(help_text='Descrição que vai aparecer na impressão')),
                ('patrimonio_editado', models.CharField(max_length=100)),
                ('numero_serie_editado', models.CharField(blank=True, max_length=100)),
                ('responsavel_receptor_nome', models.CharField(blank=True, help_text='Nome de quem recebeu', max_length=255)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_movimentacao', to='core.equipamento')),
                ('responsavel_cedente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_impressao', models.IntegerField(default=1, help_text='Nº da Ordem na folha (ex: 01)')),
                ('setor_destino', models.CharField(help_text='Ex: COORDENAÇÃO DO CENTRO CIRURGICO', max_length=255)),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('acessorios_inclusos', models.TextField(help_text='O que vai junto com o equipamento')),
                ('acessorios_pendentes', models.TextField(blank=True, help_text='Atenção: O que será entregue depois')),
                ('descricao_editada', models.CharField(help_text='Ex: MONITOR LIFEMED – M12', max_length=255)),
                ('patrimonio_editado', models.CharField(max_length=100)),
                ('responsavel_recebimento_nome', models.CharField(blank=True, max_length=255)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_entrega', to='core.equipamento')),
                ('responsavel_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_entregues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
